server:
  port: 8083
spring:
  thymeleaf:
    encoding: utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
eureka:
  instance:
    hostname: sso
  client:
    registerWithEureka: false  #当前的微服务不注册到eureka之中
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/